//! Generate Snakemake workflow files from the intermediate representation.

use crate::ir::*;

/// Generate a Snakefile from the intermediate representation.
pub fn generate_snakefile(ir: &WorkflowIR) -> String {
    let mut out = String::new();
    out.push_str("# Generated by ox export snakemake\n\n");

    // Configfile
    if let Some(ref config_file) = ir.config_file {
        out.push_str(&format!("configfile: \"{}\"\n\n", config_file));
    }

    // Includes
    for inc in &ir.includes {
        let snake_path = inc
            .replace(".toml", ".smk")
            .replace("Oxymakefile", "Snakefile");
        out.push_str(&format!("include: \"{}\"\n", snake_path));
    }
    if !ir.includes.is_empty() {
        out.push('\n');
    }

    // Rules
    for (i, rule) in ir.rules.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&generate_rule(rule));
    }

    // Diagnostics as trailing comments
    if !ir.diagnostics.is_empty() {
        out.push_str("\n# --- Export Notes ---\n");
        for diag in &ir.diagnostics {
            let prefix = match diag.level {
                DiagLevel::Info => "INFO",
                DiagLevel::Warning => "WARNING",
                DiagLevel::Error => "ERROR",
            };
            let line_info = diag
                .line
                .map(|l| format!(" (line {})", l))
                .unwrap_or_default();
            out.push_str(&format!("# {}{}: {}\n", prefix, line_info, diag.message));
        }
    }

    out
}

fn generate_rule(rule: &RuleIR) -> String {
    let mut out = String::new();
    out.push_str(&format!("rule {}:\n", rule.name));

    // Inputs
    if !rule.inputs.is_empty() {
        out.push_str("    input:\n");
        for (i, port) in rule.inputs.iter().enumerate() {
            let comma = if i < rule.inputs.len() - 1 { "," } else { "" };
            let pattern = convert_wildcards_to_snakemake(&port.pattern);
            if let Some(ref name) = port.name {
                out.push_str(&format!("        {} = \"{}\"{}\n", name, pattern, comma));
            } else {
                out.push_str(&format!("        \"{}\"{}\n", pattern, comma));
            }
        }
    }

    // Outputs
    if !rule.outputs.is_empty() {
        out.push_str("    output:\n");
        for (i, port) in rule.outputs.iter().enumerate() {
            let comma = if i < rule.outputs.len() - 1 { "," } else { "" };
            let pattern = convert_wildcards_to_snakemake(&port.pattern);
            let wrapped = wrap_output_lifecycle(&pattern, port.lifecycle.as_deref());
            if let Some(ref name) = port.name {
                out.push_str(&format!("        {} = {}{}\n", name, wrapped, comma));
            } else {
                out.push_str(&format!("        {}{}\n", wrapped, comma));
            }
        }
    }

    // Params
    if !rule.params.is_empty() {
        out.push_str("    params:\n");
        for (i, param) in rule.params.iter().enumerate() {
            let comma = if i < rule.params.len() - 1 { "," } else { "" };
            let value = convert_wildcards_to_snakemake(&param.value);
            out.push_str(&format!(
                "        {} = \"{}\"{}\n",
                param.name, value, comma
            ));
        }
    }

    // Log
    if !rule.log.is_empty() {
        out.push_str("    log:\n");
        for (i, log_path) in rule.log.iter().enumerate() {
            let comma = if i < rule.log.len() - 1 { "," } else { "" };
            let path = convert_wildcards_to_snakemake(log_path);
            out.push_str(&format!("        \"{}\"{}\n", path, comma));
        }
    }

    // Wildcard constraints
    if !rule.wildcard_constraints.is_empty() {
        out.push_str("    wildcard_constraints:\n");
        for (i, (name, constraint)) in rule.wildcard_constraints.iter().enumerate() {
            let comma = if i < rule.wildcard_constraints.len() - 1 {
                ","
            } else {
                ""
            };
            out.push_str(&format!("        {} = \"{}\"{}\n", name, constraint, comma));
        }
    }

    // Threads
    if let Some(ref threads) = rule.threads {
        match threads {
            ThreadsIR::Literal(n) => {
                out.push_str(&format!("    threads: {}\n", n));
            }
            ThreadsIR::Dynamic(expr) => {
                out.push_str(&format!("    threads: {}  # dynamic\n", expr));
            }
        }
    }

    // Resources
    if !rule.resources.is_empty() {
        out.push_str("    resources:\n");
        for (i, res) in rule.resources.iter().enumerate() {
            let comma = if i < rule.resources.len() - 1 {
                ","
            } else {
                ""
            };
            let (key, value) = translate_resource_to_snakemake(&res.key, &res.value);
            out.push_str(&format!("        {} = {}{}\n", key, value, comma));
        }
    }

    // Environment
    if let Some(ref env) = rule.environment {
        match env {
            EnvironmentIR::Conda(path) => {
                out.push_str(&format!("    conda:\n        \"{}\"\n", path));
            }
            EnvironmentIR::Container(img) => {
                let img = if !img.starts_with("docker://") {
                    format!("docker://{}", img)
                } else {
                    img.clone()
                };
                out.push_str(&format!("    container:\n        \"{}\"\n", img));
            }
            EnvironmentIR::Singularity(img) => {
                out.push_str(&format!("    singularity:\n        \"{}\"\n", img));
            }
        }
    }

    // Execution
    match &rule.execution {
        ExecutionIR::Shell(cmd) => {
            let cmd = convert_wildcards_to_snakemake(cmd);
            if cmd.contains('\n') {
                out.push_str(&format!(
                    "    shell:\n        \"\"\"\n        {}\n        \"\"\"\n",
                    cmd.replace('\n', "\n        ")
                ));
            } else {
                out.push_str(&format!("    shell:\n        \"{}\"\n", cmd));
            }
        }
        ExecutionIR::Run(code) => {
            out.push_str("    run:\n");
            for line in code.lines() {
                out.push_str(&format!("        {}\n", line));
            }
        }
        ExecutionIR::Script(path) => {
            out.push_str(&format!("    script:\n        \"{}\"\n", path));
        }
        ExecutionIR::Notebook(path) => {
            out.push_str(&format!("    notebook:\n        \"{}\"\n", path));
        }
        ExecutionIR::None => {}
    }

    out
}

/// Convert OxyMake `{wildcard}` patterns to Snakemake format.
///
/// OxyMake and Snakemake both use `{wildcard}` syntax, but OxyMake has
/// `{config.key}` which maps to `config["key"]` in Snakemake.
fn convert_wildcards_to_snakemake(s: &str) -> String {
    // Replace {config.key} with {config[key]}
    let mut result = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();

    while let Some(ch) = chars.next() {
        if ch == '{' {
            let mut inner = String::new();
            for c in chars.by_ref() {
                if c == '}' {
                    break;
                }
                inner.push(c);
            }
            if let Some(key) = inner.strip_prefix("config.") {
                result.push_str(&format!("{{config[{}]}}", key));
            } else {
                result.push('{');
                result.push_str(&inner);
                result.push('}');
            }
        } else {
            result.push(ch);
        }
    }

    result
}

/// Wrap an output pattern with a Snakemake lifecycle function if applicable.
fn wrap_output_lifecycle(pattern: &str, lifecycle: Option<&str>) -> String {
    match lifecycle {
        Some("temporary") => format!("temp(\"{}\")", pattern),
        Some("protected") => format!("protected(\"{}\")", pattern),
        _ => format!("\"{}\"", pattern),
    }
}

/// Translate OxyMake resource keys/values to Snakemake equivalents.
fn translate_resource_to_snakemake(key: &str, value: &str) -> (String, String) {
    match key {
        "cpu" => ("threads".to_string(), value.to_string()),
        "mem" => {
            // Convert human-readable sizes to mem_mb
            if let Some(gb) = value.strip_suffix('G') {
                if let Ok(n) = gb.parse::<u64>() {
                    return ("mem_mb".to_string(), (n * 1024).to_string());
                }
            }
            if let Some(mb) = value.strip_suffix('M') {
                return ("mem_mb".to_string(), mb.to_string());
            }
            ("mem_mb".to_string(), value.to_string())
        }
        "disk" => {
            if let Some(gb) = value.strip_suffix('G') {
                if let Ok(n) = gb.parse::<u64>() {
                    return ("disk_mb".to_string(), (n * 1024).to_string());
                }
            }
            if let Some(mb) = value.strip_suffix('M') {
                return ("disk_mb".to_string(), mb.to_string());
            }
            ("disk_mb".to_string(), value.to_string())
        }
        "gpu" => ("gpu".to_string(), value.to_string()),
        _ => (key.to_string(), format!("\"{}\"", value)),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_rule(name: &str) -> RuleIR {
        RuleIR {
            name: name.into(),
            inputs: vec![],
            outputs: vec![],
            execution: ExecutionIR::None,
            threads: None,
            resources: vec![],
            environment: None,
            wildcard_constraints: vec![],
            params: vec![],
            log: vec![],
            source_line: None,
            expand: None,
        }
    }

    fn make_ir(rules: Vec<RuleIR>) -> WorkflowIR {
        WorkflowIR {
            rules,
            config_file: None,
            includes: vec![],
            diagnostics: vec![],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        }
    }

    #[test]
    fn test_simple_rule() {
        let mut rule = make_rule("process");
        rule.inputs = vec![PortIR {
            name: None,
            pattern: "data/{sample}.csv".into(),
            lifecycle: None,
        }];
        rule.outputs = vec![PortIR {
            name: None,
            pattern: "results/{sample}.txt".into(),
            lifecycle: None,
        }];
        rule.execution = ExecutionIR::Shell("sort {input} > {output}".into());

        let snakefile = generate_snakefile(&make_ir(vec![rule]));
        assert!(snakefile.contains("rule process:"));
        assert!(snakefile.contains("\"data/{sample}.csv\""));
        assert!(snakefile.contains("\"results/{sample}.txt\""));
        assert!(snakefile.contains("\"sort {input} > {output}\""));
    }

    #[test]
    fn test_named_inputs() {
        let mut rule = make_rule("align");
        rule.inputs = vec![
            PortIR {
                name: Some("fastq".into()),
                pattern: "data/{sample}.fastq".into(),
                lifecycle: None,
            },
            PortIR {
                name: Some("ref".into()),
                pattern: "refs/genome.fa".into(),
                lifecycle: None,
            },
        ];
        rule.execution = ExecutionIR::Shell("bwa mem".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("fastq = \"data/{sample}.fastq\","));
        assert!(snakefile.contains("ref = \"refs/genome.fa\""));
    }

    #[test]
    fn test_temporary_output() {
        let mut rule = make_rule("step");
        rule.outputs = vec![PortIR {
            name: None,
            pattern: "tmp/file.txt".into(),
            lifecycle: Some("temporary".into()),
        }];
        rule.execution = ExecutionIR::Shell("touch {output}".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("temp(\"tmp/file.txt\")"));
    }

    #[test]
    fn test_protected_output() {
        let mut rule = make_rule("step");
        rule.outputs = vec![PortIR {
            name: None,
            pattern: "results/final.txt".into(),
            lifecycle: Some("protected".into()),
        }];
        rule.execution = ExecutionIR::Shell("touch {output}".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("protected(\"results/final.txt\")"));
    }

    #[test]
    fn test_config_wildcard_conversion() {
        assert_eq!(
            convert_wildcards_to_snakemake("{config.threads}"),
            "{config[threads]}"
        );
        assert_eq!(
            convert_wildcards_to_snakemake("data/{sample}.txt"),
            "data/{sample}.txt"
        );
        assert_eq!(
            convert_wildcards_to_snakemake("{config.key1}_{config.key2}"),
            "{config[key1]}_{config[key2]}"
        );
    }

    #[test]
    fn test_threads_and_resources() {
        let mut rule = make_rule("align");
        rule.threads = Some(ThreadsIR::Literal(8));
        rule.resources = vec![ResourceIR {
            key: "mem".into(),
            value: "16G".into(),
        }];
        rule.execution = ExecutionIR::Shell("bwa mem".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("threads: 8"));
        assert!(snakefile.contains("mem_mb = 16384"));
    }

    #[test]
    fn test_conda_environment() {
        let mut rule = make_rule("step");
        rule.environment = Some(EnvironmentIR::Conda("envs/tools.yaml".into()));
        rule.execution = ExecutionIR::Shell("echo".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("conda:"));
        assert!(snakefile.contains("\"envs/tools.yaml\""));
    }

    #[test]
    fn test_container_environment() {
        let mut rule = make_rule("step");
        rule.environment = Some(EnvironmentIR::Container("ubuntu:22.04".into()));
        rule.execution = ExecutionIR::Shell("echo".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("container:"));
        assert!(snakefile.contains("\"docker://ubuntu:22.04\""));
    }

    #[test]
    fn test_run_block() {
        let mut rule = make_rule("analyze");
        rule.execution = ExecutionIR::Run("import json\nprint('hello')".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("run:"));
        assert!(snakefile.contains("        import json"));
        assert!(snakefile.contains("        print('hello')"));
    }

    #[test]
    fn test_script() {
        let mut rule = make_rule("run_r");
        rule.execution = ExecutionIR::Script("scripts/analysis.R".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("script:"));
        assert!(snakefile.contains("\"scripts/analysis.R\""));
    }

    #[test]
    fn test_configfile() {
        let ir = WorkflowIR {
            rules: vec![],
            config_file: Some("config.yaml".into()),
            includes: vec![],
            diagnostics: vec![],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        };

        let snakefile = generate_snakefile(&ir);
        assert!(snakefile.contains("configfile: \"config.yaml\""));
    }

    #[test]
    fn test_includes() {
        let ir = WorkflowIR {
            rules: vec![],
            config_file: None,
            includes: vec!["rules/align.toml".into(), "rules/qc.toml".into()],
            diagnostics: vec![],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        };

        let snakefile = generate_snakefile(&ir);
        assert!(snakefile.contains("include: \"rules/align.smk\""));
        assert!(snakefile.contains("include: \"rules/qc.smk\""));
    }

    #[test]
    fn test_params() {
        let mut rule = make_rule("gen");
        rule.params = vec![
            ParamIR {
                name: "n_rows".into(),
                value: "100".into(),
            },
            ParamIR {
                name: "label".into(),
                value: "test".into(),
            },
        ];
        rule.execution = ExecutionIR::Shell("echo".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("params:"));
        assert!(snakefile.contains("n_rows = \"100\","));
        assert!(snakefile.contains("label = \"test\""));
    }

    #[test]
    fn test_wildcard_constraints() {
        let mut rule = make_rule("step");
        rule.wildcard_constraints = vec![("sample".into(), "[a-z]+".into())];
        rule.execution = ExecutionIR::Shell("echo".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("wildcard_constraints:"));
        assert!(snakefile.contains("sample = \"[a-z]+\""));
    }

    #[test]
    fn test_log() {
        let mut rule = make_rule("count");
        rule.log = vec!["logs/{sample}_count.log".into()];
        rule.execution = ExecutionIR::Shell("count".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("log:"));
        assert!(snakefile.contains("\"logs/{sample}_count.log\""));
    }

    #[test]
    fn test_multiline_shell() {
        let mut rule = make_rule("step");
        rule.execution = ExecutionIR::Shell("echo line1\necho line2".into());

        let snakefile = generate_rule(&rule);
        assert!(snakefile.contains("\"\"\""));
        assert!(snakefile.contains("echo line1"));
        assert!(snakefile.contains("echo line2"));
    }

    #[test]
    fn test_resource_translation() {
        assert_eq!(
            translate_resource_to_snakemake("cpu", "4"),
            ("threads".to_string(), "4".to_string())
        );
        assert_eq!(
            translate_resource_to_snakemake("mem", "16G"),
            ("mem_mb".to_string(), "16384".to_string())
        );
        assert_eq!(
            translate_resource_to_snakemake("mem", "500M"),
            ("mem_mb".to_string(), "500".to_string())
        );
        assert_eq!(
            translate_resource_to_snakemake("disk", "2G"),
            ("disk_mb".to_string(), "2048".to_string())
        );
        assert_eq!(
            translate_resource_to_snakemake("gpu", "2"),
            ("gpu".to_string(), "2".to_string())
        );
    }
}
