//! Generate WDL (Workflow Description Language) files from the intermediate representation.
//!
//! Produces WDL 1.0 compatible output. Each IR rule becomes a WDL task,
//! and a workflow block with calls is generated to wire them together.

use crate::ir::*;

/// Generate a WDL file from the intermediate representation.
pub fn generate_wdl(ir: &WorkflowIR) -> String {
    let mut out = String::new();
    out.push_str("version 1.0\n\n");
    out.push_str("# Generated by ox export wdl\n\n");

    // Imports
    for inc in &ir.includes {
        let wdl_path = inc
            .replace(".toml", ".wdl")
            .replace("Oxymakefile", "workflow");
        out.push_str(&format!("import \"{}\"\n", wdl_path));
    }
    if !ir.includes.is_empty() {
        out.push('\n');
    }

    // Tasks
    for (i, rule) in ir.rules.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&generate_task(rule));
    }

    // Workflow block
    out.push_str(&generate_workflow(ir));

    // Diagnostics as trailing comments
    if !ir.diagnostics.is_empty() {
        out.push_str("\n# --- Export Notes ---\n");
        for diag in &ir.diagnostics {
            let prefix = match diag.level {
                DiagLevel::Info => "INFO",
                DiagLevel::Warning => "WARNING",
                DiagLevel::Error => "ERROR",
            };
            let line_info = diag
                .line
                .map(|l| format!(" (line {})", l))
                .unwrap_or_default();
            out.push_str(&format!("# {}{}: {}\n", prefix, line_info, diag.message));
        }
    }

    out
}

fn generate_task(rule: &RuleIR) -> String {
    let mut out = String::new();
    out.push_str(&format!("task {} {{\n", rule.name));

    // Input section
    let has_inputs = !rule.inputs.is_empty() || !rule.params.is_empty();
    if has_inputs {
        out.push_str("    input {\n");
        for port in &rule.inputs {
            let name = port.name.as_deref().unwrap_or(&port.pattern);
            let name = sanitize_wdl_name(name);
            out.push_str(&format!("        File {}\n", name));
        }
        for param in &rule.params {
            let wdl_type = infer_wdl_type(&param.value);
            out.push_str(&format!("        {} {}\n", wdl_type, param.name));
        }
        out.push_str("    }\n\n");
    }

    // Command section
    match &rule.execution {
        ExecutionIR::Shell(cmd) => {
            let wdl_cmd = convert_placeholders_to_wdl(cmd);
            out.push_str("    command <<<\n");
            for line in wdl_cmd.lines() {
                out.push_str(&format!("        {}\n", line));
            }
            out.push_str("    >>>\n\n");
        }
        ExecutionIR::Run(code) => {
            out.push_str("    # NOTE: Inline Python code — requires wrapper script\n");
            out.push_str("    command <<<\n");
            out.push_str("        python3 -c '\n");
            for line in code.lines() {
                out.push_str(&format!("        {}\n", line));
            }
            out.push_str("        '\n");
            out.push_str("    >>>\n\n");
        }
        ExecutionIR::Script(path) => {
            out.push_str(&format!("    command <<<\n        {}\n    >>>\n\n", path));
        }
        ExecutionIR::Notebook(path) => {
            out.push_str(&format!(
                "    # NOTE: Notebook execution — requires wrapper\n    command <<<\n        jupyter nbconvert --execute {}\n    >>>\n\n",
                path
            ));
        }
        ExecutionIR::None => {}
    }

    // Output section
    if !rule.outputs.is_empty() {
        out.push_str("    output {\n");
        for port in &rule.outputs {
            let name = port.name.as_deref().unwrap_or("output_file");
            let name = sanitize_wdl_name(name);
            let pattern = convert_placeholders_to_wdl(&port.pattern);
            out.push_str(&format!("        File {} = \"{}\"\n", name, pattern));
        }
        out.push_str("    }\n\n");
    }

    // Runtime section
    let has_runtime =
        rule.environment.is_some() || rule.threads.is_some() || !rule.resources.is_empty();
    if has_runtime {
        out.push_str("    runtime {\n");

        if let Some(ref env) = rule.environment {
            match env {
                EnvironmentIR::Container(img) => {
                    let img = img.strip_prefix("docker://").unwrap_or(img);
                    out.push_str(&format!("        docker: \"{}\"\n", img));
                }
                EnvironmentIR::Singularity(img) => {
                    out.push_str(&format!("        docker: \"{}\"\n", img));
                }
                EnvironmentIR::Conda(path) => {
                    out.push_str(&format!(
                        "        # NOTE: Conda env '{}' has no WDL equivalent\n",
                        path
                    ));
                }
            }
        }

        if let Some(ref threads) = rule.threads {
            match threads {
                ThreadsIR::Literal(n) => {
                    out.push_str(&format!("        cpu: {}\n", n));
                }
                ThreadsIR::Dynamic(expr) => {
                    out.push_str(&format!("        cpu: {}  # dynamic\n", expr));
                }
            }
        }

        for res in &rule.resources {
            match res.key.as_str() {
                "mem" => {
                    let wdl_mem = convert_mem_to_wdl(&res.value);
                    out.push_str(&format!("        memory: \"{}\"\n", wdl_mem));
                }
                "disk" => {
                    let wdl_disk = convert_disk_to_wdl(&res.value);
                    out.push_str(&format!("        disks: \"{}\"\n", wdl_disk));
                }
                "gpu" => {
                    out.push_str(&format!("        gpuCount: {}\n", res.value));
                }
                _ => {
                    out.push_str(&format!("        # {}: {}\n", res.key, res.value));
                }
            }
        }

        out.push_str("    }\n");
    }

    out.push_str("}\n");
    out
}

fn generate_workflow(ir: &WorkflowIR) -> String {
    if ir.rules.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("\nworkflow generated_workflow {\n");

    // Workflow inputs from config values
    if !ir.config_values.is_empty() {
        out.push_str("    input {\n");
        for entry in &ir.config_values {
            if entry.values.len() == 1 {
                out.push_str(&format!("        String {}\n", entry.key));
            } else {
                out.push_str(&format!("        Array[String] {}\n", entry.key));
            }
        }
        out.push_str("    }\n\n");
    }

    // Calls for each task
    for rule in &ir.rules {
        if rule.expand.is_some() {
            // Scatter block
            let scatter_var = rule
                .inputs
                .first()
                .and_then(|i| i.name.as_deref())
                .unwrap_or("item");
            out.push_str(&format!(
                "    scatter ({} in {}_array) {{\n",
                scatter_var, scatter_var
            ));
            out.push_str(&format!("        call {} {{\n", rule.name));
            out.push_str("            input:\n");
            out.push_str(&format!(
                "                {} = {}\n",
                scatter_var, scatter_var
            ));
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        } else {
            out.push_str(&format!("    call {}\n", rule.name));
        }
    }

    out.push_str("}\n");
    out
}

/// Convert OxyMake `{var}` placeholders to WDL `~{var}` format.
fn convert_placeholders_to_wdl(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();

    while let Some(ch) = chars.next() {
        if ch == '{' {
            let mut inner = String::new();
            for c in chars.by_ref() {
                if c == '}' {
                    break;
                }
                inner.push(c);
            }
            // Don't convert bash variables like ${PATH} in shell commands
            // Only convert simple identifiers
            if inner
                .chars()
                .all(|c| c.is_alphanumeric() || c == '_' || c == '.')
            {
                result.push_str(&format!("~{{{}}}", inner));
            } else {
                result.push('{');
                result.push_str(&inner);
                result.push('}');
            }
        } else {
            result.push(ch);
        }
    }

    result
}

/// Sanitize a name for use as a WDL identifier.
fn sanitize_wdl_name(name: &str) -> String {
    // Remove path patterns and braces
    let name = name.replace(['{', '}'], "").replace(['/', '.'], "_");
    // Ensure it starts with a letter
    if name.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("f_{}", name)
    } else {
        name
    }
}

/// Infer a WDL type from an OxyMake param value.
fn infer_wdl_type(value: &str) -> &'static str {
    if value.parse::<i64>().is_ok() {
        "Int"
    } else if value.parse::<f64>().is_ok() {
        "Float"
    } else if value == "true" || value == "false" {
        "Boolean"
    } else {
        "String"
    }
}

/// Convert OxyMake memory format to WDL format.
fn convert_mem_to_wdl(value: &str) -> String {
    if let Some(gb) = value.strip_suffix('G') {
        format!("{} GB", gb)
    } else if let Some(mb) = value.strip_suffix('M') {
        format!("{} MB", mb)
    } else {
        format!("{} GB", value)
    }
}

/// Convert OxyMake disk format to WDL format.
fn convert_disk_to_wdl(value: &str) -> String {
    if let Some(gb) = value.strip_suffix('G') {
        format!("local-disk {} SSD", gb)
    } else if let Some(mb) = value.strip_suffix('M') {
        let gb = mb.parse::<u64>().unwrap_or(0) / 1024;
        format!("local-disk {} SSD", gb.max(1))
    } else {
        format!("local-disk {} SSD", value)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_rule(name: &str) -> RuleIR {
        RuleIR {
            name: name.into(),
            inputs: vec![],
            outputs: vec![],
            execution: ExecutionIR::None,
            threads: None,
            resources: vec![],
            environment: None,
            wildcard_constraints: vec![],
            params: vec![],
            log: vec![],
            source_line: None,
            expand: None,
        }
    }

    fn make_ir(rules: Vec<RuleIR>) -> WorkflowIR {
        WorkflowIR {
            rules,
            config_file: None,
            includes: vec![],
            diagnostics: vec![],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        }
    }

    #[test]
    fn test_simple_task_generation() {
        let mut rule = make_rule("process");
        rule.inputs = vec![PortIR {
            name: Some("input_file".into()),
            pattern: "{input_file}".into(),
            lifecycle: None,
        }];
        rule.outputs = vec![PortIR {
            name: Some("result".into()),
            pattern: "output.txt".into(),
            lifecycle: None,
        }];
        rule.execution = ExecutionIR::Shell("sort {input_file} > output.txt".into());

        let wdl = generate_wdl(&make_ir(vec![rule]));
        assert!(wdl.contains("version 1.0"));
        assert!(wdl.contains("task process {"));
        assert!(wdl.contains("File input_file"));
        assert!(wdl.contains("File result = \"output.txt\""));
        assert!(wdl.contains("sort ~{input_file} > output.txt"));
    }

    #[test]
    fn test_runtime_generation() {
        let mut rule = make_rule("heavy");
        rule.execution = ExecutionIR::Shell("run_job".into());
        rule.threads = Some(ThreadsIR::Literal(8));
        rule.resources = vec![
            ResourceIR {
                key: "mem".into(),
                value: "16G".into(),
            },
            ResourceIR {
                key: "disk".into(),
                value: "100G".into(),
            },
        ];
        rule.environment = Some(EnvironmentIR::Container("docker://ubuntu:22.04".into()));

        let wdl = generate_task(&rule);
        assert!(wdl.contains("cpu: 8"));
        assert!(wdl.contains("memory: \"16 GB\""));
        assert!(wdl.contains("disks: \"local-disk 100 SSD\""));
        assert!(wdl.contains("docker: \"ubuntu:22.04\""));
    }

    #[test]
    fn test_workflow_generation() {
        let mut rule_a = make_rule("step_a");
        rule_a.execution = ExecutionIR::Shell("echo a".into());
        rule_a.outputs = vec![PortIR {
            name: Some("out".into()),
            pattern: "a.txt".into(),
            lifecycle: None,
        }];

        let mut rule_b = make_rule("step_b");
        rule_b.execution = ExecutionIR::Shell("echo b".into());
        rule_b.inputs = vec![PortIR {
            name: Some("in_b".into()),
            pattern: "{in_b}".into(),
            lifecycle: None,
        }];

        let wdl = generate_wdl(&make_ir(vec![rule_a, rule_b]));
        assert!(wdl.contains("workflow generated_workflow {"));
        assert!(wdl.contains("call step_a"));
        assert!(wdl.contains("call step_b"));
    }

    #[test]
    fn test_scatter_generation() {
        let mut rule = make_rule("process");
        rule.inputs = vec![PortIR {
            name: Some("sample".into()),
            pattern: "{sample}".into(),
            lifecycle: None,
        }];
        rule.execution = ExecutionIR::Shell("process {sample}".into());
        rule.expand = Some("zip".to_string());

        let wdl = generate_wdl(&make_ir(vec![rule]));
        assert!(wdl.contains("scatter (sample in sample_array)"));
        assert!(wdl.contains("call process"));
    }

    #[test]
    fn test_placeholder_conversion() {
        assert_eq!(convert_placeholders_to_wdl("{sample}"), "~{sample}");
        assert_eq!(
            convert_placeholders_to_wdl("echo {name} > {output}"),
            "echo ~{name} > ~{output}"
        );
        // Bash variables should be preserved
        assert_eq!(convert_placeholders_to_wdl("{1+2}"), "{1+2}");
    }

    #[test]
    fn test_mem_conversion() {
        assert_eq!(convert_mem_to_wdl("16G"), "16 GB");
        assert_eq!(convert_mem_to_wdl("500M"), "500 MB");
    }

    #[test]
    fn test_disk_conversion() {
        assert_eq!(convert_disk_to_wdl("100G"), "local-disk 100 SSD");
        assert_eq!(convert_disk_to_wdl("2048M"), "local-disk 2 SSD");
    }

    #[test]
    fn test_includes() {
        let ir = WorkflowIR {
            rules: vec![],
            config_file: None,
            includes: vec!["rules/align.toml".into()],
            diagnostics: vec![],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        };

        let wdl = generate_wdl(&ir);
        assert!(wdl.contains("import \"rules/align.wdl\""));
    }

    #[test]
    fn test_params_as_inputs() {
        let mut rule = make_rule("gen");
        rule.params = vec![
            ParamIR {
                name: "n_rows".into(),
                value: "100".into(),
            },
            ParamIR {
                name: "label".into(),
                value: "test".into(),
            },
        ];
        rule.execution = ExecutionIR::Shell("echo {n_rows}".into());

        let wdl = generate_task(&rule);
        assert!(wdl.contains("Int n_rows"));
        assert!(wdl.contains("String label"));
    }

    #[test]
    fn test_conda_warning() {
        let mut rule = make_rule("step");
        rule.environment = Some(EnvironmentIR::Conda("envs/tools.yaml".into()));
        rule.execution = ExecutionIR::Shell("echo".into());

        let wdl = generate_task(&rule);
        assert!(wdl.contains("# NOTE: Conda env"));
    }

    #[test]
    fn test_run_block_as_python() {
        let mut rule = make_rule("analyze");
        rule.execution = ExecutionIR::Run("import json\nprint('hello')".into());

        let wdl = generate_task(&rule);
        assert!(wdl.contains("python3 -c"));
        assert!(wdl.contains("import json"));
    }
}
