//! Proptest — scheduler interleaving of cancel vs complete.
//!
//! Defends the OX-6 invariant (each job reaches at most one terminal status
//! per run) under arbitrary interleavings of the four StateDb mutations that
//! race for a single job:
//!
//! - `claim_job`  : pending → running       (atomic CAS)
//! - `complete_job`: running → completed    (atomic CAS)
//! - `fail_job`   : running → failed        (atomic CAS)
//! - `skip_job`   : pending → completed     (atomic CAS, cached=1)
//! - `cancel_job_ids`: pending|running → cancelled (atomic CAS)
//!
//! A prior fix closed the
//! Running→Cancelled hole in the scheduler; this proptest closes the
//! complementary gap: arbitrary interleavings of these five operations,
//! generated by proptest, must preserve the absorption invariant — once a
//! job lands in a terminal state, no later operation transitions it out of
//! that state.
//!
//! The reference model is a `JobState` enum mirrored in this file. After each
//! generated operation, we apply it to both (a) the StateDb and (b) the
//! reference model, then assert they agree on outcome and final status. The
//! proptest's strategy generates sequences of length 1..=N with each step a
//! `(JobIndex, Op)` pair so any pair of jobs can race in any order.

use std::path::PathBuf;

use ox_state::db::{JobRecord, StateDb};
use proptest::collection::vec;
use proptest::prelude::*;
use tempfile::TempDir;

// ---------------------------------------------------------------------------
// Reference model — the SQL guards expressed in pure Rust.
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum JobState {
    Pending,
    Running,
    Completed,
    Failed,
    Cancelled,
}

impl JobState {
    fn is_terminal(self) -> bool {
        matches!(self, Self::Completed | Self::Failed | Self::Cancelled)
    }
}

#[derive(Debug, Clone, Copy)]
enum Op {
    Claim,
    Complete,
    Fail,
    Skip,
    Cancel,
}

/// Apply `op` to `state` under the same guards the StateDb uses.
/// Returns `(new_state, transitioned)`.
fn step(state: JobState, op: Op) -> (JobState, bool) {
    match (state, op) {
        (JobState::Pending, Op::Claim) => (JobState::Running, true),
        (JobState::Running, Op::Complete) => (JobState::Completed, true),
        (JobState::Running, Op::Fail) => (JobState::Failed, true),
        (JobState::Pending, Op::Skip) => (JobState::Completed, true),
        (JobState::Pending, Op::Cancel) | (JobState::Running, Op::Cancel) => {
            (JobState::Cancelled, true)
        }
        // Any other (state, op) pair is a no-op — the SQL CHECK constraint
        // and the `WHERE status IN (...)` clauses make these UPDATEs match
        // zero rows.
        _ => (state, false),
    }
}

fn db_status_to_state(s: &str) -> JobState {
    match s {
        "pending" => JobState::Pending,
        "running" => JobState::Running,
        "completed" => JobState::Completed,
        "failed" => JobState::Failed,
        "cancelled" => JobState::Cancelled,
        other => panic!("unexpected status from StateDb: {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

const JOB_COUNT: usize = 4;
const SESSION_PID: u32 = 4242;

fn fresh_db() -> (TempDir, PathBuf, StateDb, String) {
    let dir = TempDir::new().unwrap();
    let db_path = dir.path().join("state.db");
    let db = StateDb::open(&db_path).unwrap();
    db.begin_run("run-prop", None, JOB_COUNT, None).unwrap();
    let jobs: Vec<JobRecord> = (0..JOB_COUNT)
        .map(|i| JobRecord {
            id: format!("j{i}"),
            rule_name: "build".into(),
            wildcards: "{}".into(),
            cache_key: None,
            run_id: Some("run-prop".into()),
        })
        .collect();
    db.register_jobs(&jobs).unwrap();
    let session = db.create_session(SESSION_PID, "proptest", None).unwrap();
    (dir, db_path, db, session)
}

fn job_id(index: usize) -> String {
    format!("j{index}")
}

// ---------------------------------------------------------------------------
// Strategy
// ---------------------------------------------------------------------------

fn op_strategy() -> impl Strategy<Value = Op> {
    prop_oneof![
        Just(Op::Claim),
        Just(Op::Complete),
        Just(Op::Fail),
        Just(Op::Skip),
        Just(Op::Cancel),
    ]
}

fn step_strategy() -> impl Strategy<Value = (usize, Op)> {
    (0..JOB_COUNT, op_strategy())
}

fn program_strategy() -> impl Strategy<Value = Vec<(usize, Op)>> {
    // Length 1..=24 — long enough to interleave several jobs through their
    // whole lifecycle, short enough that proptest can shrink in finite time.
    vec(step_strategy(), 1..=24)
}

// ---------------------------------------------------------------------------
// The property
// ---------------------------------------------------------------------------

// Random interleavings of {claim, complete, fail, skip, cancel} on a
// pool of `JOB_COUNT` jobs preserve every load-bearing invariant:
//
// 1. Each operation's outcome matches the reference model (i.e., the
//    SQL guards are equivalent to the pure-function `step` above).
// 2. The DB final status matches the model's final state.
// 3. No job ever transitions out of a terminal state.
// 4. After `finalize_job_history`, the OX-6 audit-trail invariant
//    (`terminal_status_violations` empty) holds.
proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        max_shrink_iters: 4096,
        .. ProptestConfig::default()
    })]
    #[test]
    fn cancel_vs_complete_interleaving_preserves_invariants(
        program in program_strategy(),
    ) {
        let (_dir, _path, db, session) = fresh_db();
        let mut model = vec![JobState::Pending; JOB_COUNT];
        // Track every state each job has visited, so we can assert that once
        // a job enters a terminal state it never leaves it.
        let mut history: Vec<Vec<JobState>> = (0..JOB_COUNT)
            .map(|_| vec![JobState::Pending])
            .collect();

        for (i, (idx, op)) in program.iter().enumerate() {
            let id = job_id(*idx);
            let before = model[*idx];
            let (expected_after, expected_transitioned) = step(before, *op);

            let actual_transitioned = match op {
                Op::Claim => db.claim_job(&id, &session).unwrap(),
                Op::Complete => db.complete_job(&id, &session, 0, "{}").unwrap(),
                Op::Fail => db.fail_job(&id, &session, 1).unwrap(),
                Op::Skip => db.skip_job(&id).unwrap(),
                Op::Cancel => {
                    let cancelled = db.cancel_job_ids(&[id.clone()]).unwrap();
                    !cancelled.is_empty()
                }
            };

            prop_assert_eq!(
                actual_transitioned, expected_transitioned,
                "step {}: op={:?} before={:?} — DB and model disagree on transition outcome",
                i, op, before
            );

            model[*idx] = expected_after;
            history[*idx].push(expected_after);

            // Invariant 3 — terminal states are absorbing in the model.
            // We also check the DB agrees by reading back the status.
            let db_status = db
                .job_status(&id)
                .unwrap()
                .expect("job must exist after register_jobs");
            let db_state = db_status_to_state(&db_status);
            prop_assert_eq!(
                db_state, expected_after,
                "step {}: job {} DB status {:?} ≠ model {:?}",
                i, id, db_state, expected_after
            );
        }

        // Invariant 3 (post-mortem): walk each job's history and check that
        // no terminal → non-terminal transition occurred.
        for (idx, states) in history.iter().enumerate() {
            let mut seen_terminal: Option<JobState> = None;
            for &s in states {
                if let Some(t) = seen_terminal {
                    prop_assert_eq!(
                        s, t,
                        "job j{}: transitioned out of terminal {:?} into {:?}",
                        idx, t, s
                    );
                }
                if s.is_terminal() && seen_terminal.is_none() {
                    seen_terminal = Some(s);
                }
            }
        }

        // Invariant 4 — the OX-6 audit-trail invariant must hold for any
        // arbitrary interleaving, including those that finalize the run.
        db
            .finalize_job_history("run-prop", "local", "proptest", &Default::default())
            .unwrap();
        let violations = db.terminal_status_violations().unwrap();
        prop_assert!(
            violations.is_empty(),
            "OX-6 violated under interleaving {:?} — violations={:?}",
            program, violations
        );
    }
}
