#!/usr/bin/env python3
"""Generate a synthetic Oxymakefile for benchmarking transport overhead.

Creates a linear chain of N identity jobs, each copying input→output.
Configurable: number of jobs, output size, and execution mode.

Usage:
    python bench/synthetic/generate.py --jobs 50 --size 1M > bench/synthetic/Oxymakefile.toml
    python bench/synthetic/generate.py --jobs 50 --size 1M --materialize auto > bench/synthetic/Oxymakefile-memory.toml
"""
import argparse
import sys

def parse_size(s: str) -> int:
    """Parse human-readable size: 1K, 1M, 10M, 1G."""
    s = s.strip().upper()
    multipliers = {'K': 1024, 'M': 1024**2, 'G': 1024**3}
    if s[-1] in multipliers:
        return int(s[:-1]) * multipliers[s[-1]]
    return int(s)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--jobs', type=int, default=50)
    parser.add_argument('--size', type=str, default='1M', help='Output size per job')
    parser.add_argument('--materialize', type=str, default='always',
                        choices=['always', 'auto', 'never'])
    args = parser.parse_args()

    size = parse_size(args.size)
    mat = args.materialize

    print(f'# Synthetic benchmark: {args.jobs} identity jobs, {args.size} per output')
    print(f'# materialize = "{mat}"')
    print(f'# Generated by bench/synthetic/generate.py')
    print()
    print('ox_version = "0.1"')
    print()
    print('[config]')
    print('results_dir = "bench_output"')
    print()

    # Seed job: creates initial data
    print('# Seed: create initial random data')
    print('[rule.seed]')
    if mat != 'always':
        print(f'output = [{{ path = "{{config.results_dir}}/step_000.bin", materialize = "{mat}" }}]')
    else:
        print('output = ["{config.results_dir}/step_000.bin"]')
    print(f'shell = "dd if=/dev/urandom of={{config.results_dir}}/step_000.bin bs={size} count=1 2>/dev/null"')
    print()

    # Chain jobs
    for i in range(1, args.jobs):
        prev = f'{{config.results_dir}}/step_{i-1:03d}.bin'
        curr = f'{{config.results_dir}}/step_{i:03d}.bin'
        print(f'[rule.step_{i:03d}]')
        print(f'input = ["{prev}"]')
        if mat != 'always':
            print(f'output = [{{ path = "{curr}", materialize = "{mat}" }}]')
        else:
            print(f'output = ["{curr}"]')
        print(f'shell = "python3 bench/synthetic/identity.py {prev} {curr}"')
        print()

    # All target
    last = f'{{config.results_dir}}/step_{args.jobs-1:03d}.bin'
    print('[rule.all]')
    print(f'input = ["{last}"]')

if __name__ == '__main__':
    main()
