#!/usr/bin/env bash
# Regenerate docs/paper/metrics.tex from metrics/metrics.json.
#
# Per ADR-016, this script is the paper-surface CONSUMER of the canonical
# metrics file. The PRODUCER lives at scripts/regenerate-metrics.sh and
# populates metrics/metrics.json from live workspace measurements. This
# script then renders the LaTeX surface form (\newcommand macros with
# LaTeX-safe thousands grouping) expected by oxymake-paper.tex.
#
# History : this script used to compute SLOC / tests / commits / ...
# itself. The metrics deliberation §3 T2 showed the values it produced
# drifted against README and benchmark surfaces (62/102/688 ms triple-
# drift on dag_resolution_10k_ms). ADR-016 collapses the producers into
# one ; this script became a thin renderer of the canonical JSON.
#
# Macros NOT auto-derived (kept manual in oxymake-paper.tex):
#   \metricDocTests  -- doc tests are mixed into cargo's test output ;
#                       separating them reliably is brittle.
#   \metricMaxAgents -- peak concurrent agent count is an editorial
#                       claim, not a code measurement.
#   \metricCoverage  -- cargo llvm-cov forces a fully instrumented
#                       rebuild and is too slow to run on every paper
#                       build. Refresh manually with
#                       OXYMAKE_REGEN_COVERAGE=1 to print the current
#                       coverage on stderr (then update the macro by
#                       hand in oxymake-paper.tex).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$ROOT"

err() { printf 'regenerate-metrics: %s\n' "$*" >&2; }

require() {
    if ! command -v "$1" >/dev/null 2>&1; then
        err "required tool '$1' not found in PATH"
        exit 1
    fi
}

require jq

METRICS_JSON="metrics/metrics.json"

# Ensure the canonical file exists ; regenerate it on demand if missing.
# This keeps `make` inside docs/paper a single-command workflow for
# operators who don't routinely run the top-level Makefile.
if [ ! -f "$METRICS_JSON" ]; then
    err "canonical $METRICS_JSON missing — running workspace producer first"
    bash scripts/regenerate-metrics.sh
fi

read_metric() {
    local key="$1"
    jq -r --arg k "$key" '(.[$k].value // empty)' "$METRICS_JSON"
}

SLOC=$(read_metric sloc)
TESTS=$(read_metric tests)
CRATES=$(read_metric crates)
COMMITS=$(read_metric commits)
DEVDAYS=$(read_metric dev_days)
DOCFILES=$(read_metric doc_files)

for var in SLOC TESTS CRATES COMMITS DEVDAYS DOCFILES; do
    val="${!var}"
    if [ -z "$val" ]; then
        err "metric '$var' missing from $METRICS_JSON ; re-run scripts/regenerate-metrics.sh"
        exit 1
    fi
done

# Coverage: opt-in summary (not emitted to metrics.tex). Operator updates
# \metricCoverage in oxymake-paper.tex by hand when refreshing the paper.
if [ "${OXYMAKE_REGEN_COVERAGE:-0}" = "1" ] && command -v cargo-llvm-cov >/dev/null 2>&1; then
    COV_RAW=$(cargo llvm-cov --workspace --summary-only 2>/dev/null \
              | awk '/^TOTAL/ {gsub("%", "", $NF); print $NF; exit}')
    if printf '%s' "${COV_RAW:-}" | grep -Eq '^[0-9]+(\.[0-9]+)?$'; then
        err "coverage (llvm-cov line %): $COV_RAW -- update \\metricCoverage in oxymake-paper.tex if changed"
    else
        err "coverage parse failed; cargo llvm-cov output did not match expected pattern"
    fi
fi

# Use comma thousands separator for the two largest counts to match the
# paper's prior typographic convention (\metricSLOC, \metricTests).
group_thousands() {
    # Renders 58966 as "58{,}966" (LaTeX-safe thousands group).
    printf '%s' "$1" | awk '
        {
            n = $1; out = ""
            while (length(n) > 3) {
                out = "{,}" substr(n, length(n)-2) out
                n = substr(n, 1, length(n)-3)
            }
            print n out
        }'
}

SLOC_TEX=$(group_thousands "$SLOC")
TESTS_TEX=$(group_thousands "$TESTS")
COMMITS_TEX=$(group_thousands "$COMMITS")

OUT="docs/paper/metrics.tex"
cat > "$OUT" <<EOF
% Auto-generated by docs/paper/scripts/regenerate-metrics.sh on $(date -u +%Y-%m-%d)
% DO NOT EDIT BY HAND -- the source of truth is metrics/metrics.json (ADR-016).
% This file is regenerated by the paper Makefile via 'make metrics' before
% every build of oxymake-paper.pdf.
\newcommand{\metricSLOC}{${SLOC_TEX}}
\newcommand{\metricTests}{${TESTS_TEX}}
\newcommand{\metricCrates}{${CRATES}}
\newcommand{\metricCommits}{${COMMITS_TEX}}
\newcommand{\metricDevDays}{${DEVDAYS}}
\newcommand{\metricDocFiles}{${DOCFILES}}
EOF

err "wrote $OUT from $METRICS_JSON (SLOC=$SLOC TESTS=$TESTS CRATES=$CRATES COMMITS=$COMMITS DEVDAYS=$DEVDAYS DOCFILES=$DOCFILES)"
