.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ox-import 1  "ox-import " 
.SH NAME
ox\-import \- Adopt verified outputs described by a portable manifest
.SH SYNOPSIS
\fBox\-import\fR [\fB\-f\fR|\fB\-\-file\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIMANIFEST\fR> 
.SH DESCRIPTION
Adopt verified outputs described by a portable manifest
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-file\fR \fI<FILE>\fR [default: Oxymakefile.toml]
Oxymakefile path
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIMANIFEST\fR>
Versioned adoption manifest produced by `ox export \-\-manifest`
