.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ox-snapshot-delete 1  "ox-snapshot-delete " 
.SH NAME
ox\-snapshot\-delete \- Delete a snapshot
.SH SYNOPSIS
\fBox\-snapshot\-delete\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Delete a snapshot
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Snapshot name to delete
