use crate::ir::*;

/// Generate an Oxymakefile.toml from the intermediate representation.
pub fn generate_oxymakefile(ir: &WorkflowIR) -> String {
    let mut out = String::new();
    out.push_str("# Generated by ox-translate from Snakemake\n");
    out.push_str("ox_version = \"0.1\"\n\n");

    // Config section
    if !ir.config_values.is_empty() {
        out.push_str("[config]\n");
        for entry in &ir.config_values {
            if entry.values.len() == 1 {
                out.push_str(&format!("{} = \"{}\"\n", entry.key, entry.values[0]));
            } else {
                out.push_str(&format!("{} = [", entry.key));
                let quoted: Vec<String> =
                    entry.values.iter().map(|v| format!("\"{}\"", v)).collect();
                out.push_str(&quoted.join(", "));
                out.push_str("]\n");
            }
        }
        out.push('\n');
    } else if let Some(ref config_file) = ir.config_file {
        // configfile was declared but YAML resolution didn't populate config_values
        // (e.g., file not found, or resolve_config was not called)
        out.push_str(&format!(
            "# TODO: Convert {} to [config] section below\n",
            config_file
        ));
        out.push_str(&format!("# configfile: \"{}\"\n\n", config_file));
    }

    // Includes
    if !ir.includes.is_empty() {
        out.push_str("include = [\n");
        for inc in &ir.includes {
            let toml_path = inc.replace(".smk", ".toml").replace(".snakefile", ".toml");
            out.push_str(&format!("    \"{}\",\n", toml_path));
        }
        out.push_str("]\n\n");
    }

    // Rules
    for rule in &ir.rules {
        out.push_str(&generate_rule(rule));
    }

    // Diagnostics as trailing comments
    if !ir.diagnostics.is_empty() {
        out.push_str("# --- Translation Notes ---\n");
        for diag in &ir.diagnostics {
            let prefix = match diag.level {
                DiagLevel::Info => "INFO",
                DiagLevel::Warning => "WARNING",
                DiagLevel::Error => "ERROR",
            };
            let line_info = diag
                .line
                .map(|l| format!(" (line {})", l))
                .unwrap_or_default();
            out.push_str(&format!("# {}{}: {}\n", prefix, line_info, diag.message));
        }
    }

    out
}

/// Generate a structured escalation sidecar file (TOML).
pub fn generate_escalation_file(ir: &WorkflowIR) -> Option<String> {
    if ir.escalations.is_empty() {
        return None;
    }

    let mut out = String::new();
    out.push_str(
        "# Translation escalations — structured instructions for agent/human resolution\n",
    );
    out.push_str("# Generated by ox-translate. Do not edit manually.\n\n");

    let tier_counts = (
        ir.escalations
            .iter()
            .filter(|e| e.tier == EscalationTier::MechanicalDeferred)
            .count(),
        ir.escalations
            .iter()
            .filter(|e| e.tier == EscalationTier::Assisted)
            .count(),
        ir.escalations
            .iter()
            .filter(|e| e.tier == EscalationTier::Human)
            .count(),
    );

    out.push_str("[meta]\n");
    out.push_str(&format!("total_escalations = {}\n", ir.escalations.len()));
    out.push_str(&format!(
        "tier_counts = {{ mechanical_deferred = {}, assisted = {}, human = {} }}\n\n",
        tier_counts.0, tier_counts.1, tier_counts.2
    ));

    for esc in &ir.escalations {
        out.push_str("[[escalation]]\n");
        out.push_str(&format!("id = \"{}\"\n", esc.id));
        out.push_str(&format!("tier = \"{:?}\"\n", esc.tier));
        out.push_str(&format!("category = \"{:?}\"\n", esc.category));
        out.push_str(&format!("severity = \"{:?}\"\n", esc.severity));
        if let Some(ref rule) = esc.rule_name {
            out.push_str(&format!("rule_name = \"{}\"\n", rule));
        }
        out.push_str(&format!(
            "construct = \"{}\"\n",
            escape_toml_string(&esc.construct)
        ));
        if let Some(line) = esc.source_line {
            out.push_str(&format!("source_line = {}\n", line));
        }
        out.push_str(&format!(
            "original_code = \"\"\"\n{}\n\"\"\"\n",
            esc.original_code
        ));

        // Context
        let ctx = &esc.context;
        if ctx.function_name.is_some()
            || ctx.data_file.is_some()
            || ctx.directive_name.is_some()
            || ctx.config_key.is_some()
        {
            out.push_str("[escalation.context]\n");
            if let Some(ref f) = ctx.function_name {
                out.push_str(&format!("function_name = \"{}\"\n", f));
            }
            if let Some(ref d) = ctx.data_file {
                out.push_str(&format!("data_file = \"{}\"\n", d));
            }
            if let Some(ref d) = ctx.directive_name {
                out.push_str(&format!("directive_name = \"{}\"\n", d));
            }
            if let Some(ref v) = ctx.directive_value {
                out.push_str(&format!(
                    "directive_value = \"{}\"\n",
                    escape_toml_string(v)
                ));
            }
            if let Some(ref k) = ctx.config_key {
                out.push_str(&format!("config_key = \"{}\"\n", k));
            }
        }

        // Instructions
        out.push_str("[escalation.instructions]\n");
        out.push_str(&format!(
            "summary = \"{}\"\n",
            escape_toml_string(&esc.instructions.summary)
        ));
        out.push_str("steps = [\n");
        for step in &esc.instructions.steps {
            out.push_str(&format!("    \"{}\",\n", escape_toml_string(step)));
        }
        out.push_str("]\n");
        out.push_str("acceptance_criteria = [\n");
        for crit in &esc.instructions.acceptance_criteria {
            out.push_str(&format!("    \"{}\",\n", escape_toml_string(crit)));
        }
        out.push_str("]\n\n");
    }

    Some(out)
}

fn generate_rule(rule: &RuleIR) -> String {
    let mut out = String::new();
    out.push_str(&format!("[rule.{}]\n", rule.name));

    // Source line — emitted so ox-plan errors can cite the original source
    // location when this Oxymakefile was produced by `ox translate`.
    if let Some(line) = rule.source_line {
        out.push_str(&format!("source_line = {}\n", line));
    }

    // Inputs
    if !rule.inputs.is_empty() {
        let has_named = rule.inputs.iter().any(|p| p.name.is_some());
        if has_named {
            out.push_str("input = { ");
            let parts: Vec<String> = rule
                .inputs
                .iter()
                .map(|p| {
                    if let Some(ref name) = p.name {
                        format!("{} = \"{}\"", name, p.pattern)
                    } else {
                        format!("\"{}\"", p.pattern)
                    }
                })
                .collect();
            out.push_str(&parts.join(", "));
            out.push_str(" }\n");
        } else {
            out.push_str("input = [\n");
            for p in &rule.inputs {
                if p.pattern.starts_with("expand:") {
                    let pattern = &p.pattern["expand:".len()..];
                    out.push_str(&format!(
                        "    \"{}\",  # TODO: configure expand variables in [config]\n",
                        pattern
                    ));
                } else if p.pattern.starts_with("# MANUAL:") {
                    out.push_str(&format!("    # MANUAL: {}\n", &p.pattern[9..]));
                } else {
                    out.push_str(&format!("    \"{}\",\n", p.pattern));
                }
            }
            out.push_str("]\n");
        }
    }

    // Expand mode (e.g., product for Cartesian expansion of wildcards)
    if let Some(ref mode) = rule.expand {
        out.push_str(&format!("expand = \"{}\"\n", mode));
    }

    // Outputs — use named map if any output has a name
    if !rule.outputs.is_empty() {
        let has_named = rule.outputs.iter().any(|p| p.name.is_some());
        let has_lifecycle = rule.outputs.iter().any(|p| p.lifecycle.is_some());

        if has_named && !has_lifecycle {
            // Named map: output = { name = "path", ... }
            out.push_str("output = { ");
            let parts: Vec<String> = rule
                .outputs
                .iter()
                .map(|p| {
                    if let Some(ref name) = p.name {
                        format!("{} = \"{}\"", name, p.pattern)
                    } else {
                        format!("\"{}\"", p.pattern)
                    }
                })
                .collect();
            out.push_str(&parts.join(", "));
            out.push_str(" }\n");
        } else {
            out.push_str("output = [\n");
            for p in &rule.outputs {
                if let Some(ref lifecycle) = p.lifecycle {
                    if let Some(ref name) = p.name {
                        out.push_str(&format!(
                            "    {{ path = \"{}\", name = \"{}\", lifecycle = \"{}\" }},\n",
                            p.pattern, name, lifecycle
                        ));
                    } else {
                        out.push_str(&format!(
                            "    {{ path = \"{}\", lifecycle = \"{}\" }},\n",
                            p.pattern, lifecycle
                        ));
                    }
                } else {
                    out.push_str(&format!("    \"{}\",\n", p.pattern));
                }
            }
            out.push_str("]\n");
        }
    }

    // Params
    if !rule.params.is_empty() {
        let simple_params: Vec<&ParamIR> = rule
            .params
            .iter()
            .filter(|p| !p.value.starts_with("# MANUAL:"))
            .collect();
        let complex_params: Vec<&ParamIR> = rule
            .params
            .iter()
            .filter(|p| p.value.starts_with("# MANUAL:"))
            .collect();

        if !simple_params.is_empty() {
            out.push_str("params = { ");
            let parts: Vec<String> = simple_params
                .iter()
                .map(|p| {
                    // Try to detect if value is numeric
                    if p.value.parse::<f64>().is_ok() || p.value == "true" || p.value == "false" {
                        format!("{} = {}", p.name, p.value)
                    } else {
                        format!("{} = \"{}\"", p.name, p.value)
                    }
                })
                .collect();
            out.push_str(&parts.join(", "));
            out.push_str(" }\n");
        }
        for p in &complex_params {
            let desc = p.value.strip_prefix("# MANUAL: ").unwrap_or(&p.value);
            out.push_str(&format!("# params.{}: {}\n", p.name, desc));
        }
    }

    // Log
    if !rule.log.is_empty() {
        if rule.log.len() == 1 {
            out.push_str(&format!(
                "log = {{ stdout = \"{}\", stderr = \"{}\" }}\n",
                rule.log[0], rule.log[0]
            ));
        } else {
            out.push_str(&format!(
                "log = {{ stdout = \"{}\", stderr = \"{}\" }}\n",
                rule.log[0],
                rule.log.get(1).unwrap_or(&rule.log[0])
            ));
        }
    }

    // Execution
    match &rule.execution {
        ExecutionIR::Shell(cmd) => {
            if cmd.contains('\n') {
                out.push_str(&format!("shell = \"\"\"\n{}\n\"\"\"\n", cmd));
            } else {
                out.push_str(&format!("shell = \"{}\"\n", escape_toml_string(cmd)));
            }
        }
        ExecutionIR::Run(code) => {
            out.push_str("lang = \"python\"\n");
            // Prefer a TOML *literal* multi-line string: basic `"""` strings
            // process backslash escapes, which corrupts Python code such as
            // `'\n'.join(...)`. Literal strings pass the code through verbatim.
            if code.contains("'''") {
                out.push_str(&format!("run = \"\"\"\n{}\n\"\"\"\n", code));
            } else {
                out.push_str(&format!("run = '''\n{}\n'''\n", code));
            }
        }
        ExecutionIR::Script(path) => {
            out.push_str(&format!("script = \"{}\"\n", path));
        }
        ExecutionIR::Notebook(path) => {
            out.push_str(&format!(
                "# notebook translated as script\nscript = \"{}\"\n",
                path
            ));
        }
        ExecutionIR::None => {}
    }

    // Resources (threads -> cpu)
    let literal_threads = rule.threads.as_ref().and_then(|t| t.as_literal());
    if literal_threads.is_some() || !rule.resources.is_empty() {
        out.push_str("resources = { ");
        let mut parts = Vec::new();
        if let Some(threads) = literal_threads {
            parts.push(format!("cpu = {}", threads));
        }
        for res in &rule.resources {
            let (key, value) = translate_resource(&res.key, &res.value);
            parts.push(format!("{} = {}", key, value));
        }
        out.push_str(&parts.join(", "));
        out.push_str(" }\n");
    }

    // Environment
    if let Some(ref env) = rule.environment {
        match env {
            EnvironmentIR::Conda(path) => {
                out.push_str(&format!("environment = {{ conda = \"{}\" }}\n", path));
            }
            EnvironmentIR::Container(img) => {
                let img = img.strip_prefix("docker://").unwrap_or(img);
                out.push_str(&format!("environment = {{ docker = \"{}\" }}\n", img));
            }
            EnvironmentIR::Singularity(img) => {
                out.push_str(&format!("environment = {{ apptainer = \"{}\" }}\n", img));
            }
        }
    }

    // Wildcard constraints
    if !rule.wildcard_constraints.is_empty() {
        out.push_str(&format!("\n[rule.{}.wildcard_constraints]\n", rule.name));
        for (name, constraint) in &rule.wildcard_constraints {
            out.push_str(&format!("{} = \"{}\"\n", name, constraint));
        }
    }

    out.push('\n');
    out
}

/// Translate Snakemake resource keys/values to OxyMake equivalents.
fn translate_resource(key: &str, value: &str) -> (String, String) {
    let clean_value = value.trim_end_matches(',').trim();

    match key {
        "mem_mb" => {
            if let Ok(mb) = clean_value.parse::<u64>() {
                if mb >= 1024 && mb % 1024 == 0 {
                    ("mem".to_string(), format!("\"{}G\"", mb / 1024))
                } else {
                    ("mem".to_string(), format!("\"{}M\"", mb))
                }
            } else {
                ("mem".to_string(), format!("\"{}M\"", clean_value))
            }
        }
        "disk_mb" => {
            if let Ok(mb) = clean_value.parse::<u64>() {
                if mb >= 1024 && mb % 1024 == 0 {
                    ("disk".to_string(), format!("\"{}G\"", mb / 1024))
                } else {
                    ("disk".to_string(), format!("\"{}M\"", mb))
                }
            } else {
                ("disk".to_string(), format!("\"{}M\"", clean_value))
            }
        }
        "gpu" => ("gpu".to_string(), clean_value.to_string()),
        _ => (key.to_string(), format!("\"{}\"", clean_value)),
    }
}

fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_rule(name: &str) -> RuleIR {
        RuleIR {
            name: name.into(),
            inputs: vec![],
            outputs: vec![],
            execution: ExecutionIR::None,
            threads: None,
            resources: vec![],
            environment: None,
            wildcard_constraints: vec![],
            params: vec![],
            log: vec![],
            source_line: None,
            expand: None,
        }
    }

    fn make_ir(rules: Vec<RuleIR>) -> WorkflowIR {
        WorkflowIR {
            rules,
            config_file: None,
            includes: vec![],
            diagnostics: vec![],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        }
    }

    #[test]
    fn test_generate_simple_rule() {
        let mut rule = make_rule("process");
        rule.inputs = vec![PortIR {
            name: None,
            pattern: "data/{sample}.csv".into(),
            lifecycle: None,
        }];
        rule.outputs = vec![PortIR {
            name: None,
            pattern: "results/{sample}.txt".into(),
            lifecycle: None,
        }];
        rule.execution = ExecutionIR::Shell("sort {input} > {output}".into());

        let toml = generate_oxymakefile(&make_ir(vec![rule]));
        assert!(toml.contains("[rule.process]"));
        assert!(toml.contains(r#""data/{sample}.csv""#));
        assert!(toml.contains(r#""results/{sample}.txt""#));
        assert!(toml.contains(r#"shell = "sort {input} > {output}""#));
    }

    #[test]
    fn test_generate_named_inputs() {
        let mut rule = make_rule("align");
        rule.inputs = vec![
            PortIR {
                name: Some("fastq".into()),
                pattern: "data/{sample}.fastq".into(),
                lifecycle: None,
            },
            PortIR {
                name: Some("ref".into()),
                pattern: "refs/genome.fa".into(),
                lifecycle: None,
            },
        ];
        rule.execution = ExecutionIR::Shell("bwa mem".into());

        let toml = generate_rule(&rule);
        assert!(
            toml.contains("input = { fastq = \"data/{sample}.fastq\", ref = \"refs/genome.fa\" }")
        );
    }

    #[test]
    fn test_generate_named_outputs() {
        let mut rule = make_rule("count");
        rule.outputs = vec![
            PortIR {
                name: Some("counts".into()),
                pattern: "results/{sample}_counts.txt".into(),
                lifecycle: None,
            },
            PortIR {
                name: Some("summary".into()),
                pattern: "results/{sample}_summary.txt".into(),
                lifecycle: None,
            },
        ];
        rule.execution = ExecutionIR::Shell("count {input}".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("output = { counts = \"results/{sample}_counts.txt\", summary = \"results/{sample}_summary.txt\" }"));
    }

    #[test]
    fn test_generate_lifecycle_outputs() {
        let mut rule = make_rule("step");
        rule.outputs = vec![PortIR {
            name: None,
            pattern: "tmp/file.txt".into(),
            lifecycle: Some("temporary".into()),
        }];
        rule.execution = ExecutionIR::Shell("touch {output}".into());

        let toml = generate_oxymakefile(&make_ir(vec![rule]));
        assert!(toml.contains(r#"path = "tmp/file.txt", lifecycle = "temporary""#));
    }

    #[test]
    fn test_generate_named_output_with_lifecycle() {
        let mut rule = make_rule("step");
        rule.outputs = vec![PortIR {
            name: Some("tmp".into()),
            pattern: "tmp/file.txt".into(),
            lifecycle: Some("temporary".into()),
        }];
        rule.execution = ExecutionIR::Shell("touch {output}".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains(r#"path = "tmp/file.txt", name = "tmp", lifecycle = "temporary""#));
    }

    #[test]
    fn test_generate_params() {
        let mut rule = make_rule("gen");
        rule.params = vec![
            ParamIR {
                name: "n_rows".into(),
                value: "100".into(),
            },
            ParamIR {
                name: "label".into(),
                value: "test".into(),
            },
        ];
        rule.execution = ExecutionIR::Shell("echo {params.n_rows}".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("params = { n_rows = 100, label = \"test\" }"));
    }

    #[test]
    fn test_generate_complex_params() {
        let mut rule = make_rule("gen");
        rule.params = vec![
            ParamIR {
                name: "simple".into(),
                value: "42".into(),
            },
            ParamIR {
                name: "extra".into(),
                value: "# MANUAL: lambda wc: compute(wc)".into(),
            },
        ];
        rule.execution = ExecutionIR::Shell("echo".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("params = { simple = 42 }"));
        assert!(toml.contains("# params.extra: lambda wc: compute(wc)"));
    }

    #[test]
    fn test_generate_log() {
        let mut rule = make_rule("count");
        rule.log = vec!["logs/{sample}_count.log".into()];
        rule.execution = ExecutionIR::Shell("count {input}".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains(
            r#"log = { stdout = "logs/{sample}_count.log", stderr = "logs/{sample}_count.log" }"#
        ));
    }

    #[test]
    fn test_generate_log_two_paths() {
        let mut rule = make_rule("proc");
        rule.log = vec!["logs/out.log".into(), "logs/err.log".into()];
        rule.execution = ExecutionIR::Shell("run".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains(r#"log = { stdout = "logs/out.log", stderr = "logs/err.log" }"#));
    }

    #[test]
    fn test_generate_with_threads_and_conda() {
        let mut rule = make_rule("align");
        rule.inputs = vec![PortIR {
            name: Some("fastq".into()),
            pattern: "data/{sample}.fastq".into(),
            lifecycle: None,
        }];
        rule.outputs = vec![PortIR {
            name: None,
            pattern: "results/{sample}.bam".into(),
            lifecycle: None,
        }];
        rule.execution = ExecutionIR::Shell("bwa mem {input.fastq} > {output}".into());
        rule.threads = Some(ThreadsIR::Literal(8));
        rule.resources = vec![ResourceIR {
            key: "mem_mb".into(),
            value: "16000".into(),
        }];
        rule.environment = Some(EnvironmentIR::Conda("envs/alignment.yaml".into()));

        let ir = WorkflowIR {
            rules: vec![rule],
            config_file: Some("config.yaml".into()),
            includes: vec![],
            diagnostics: vec![],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        };

        let toml = generate_oxymakefile(&ir);
        assert!(toml.contains("# TODO: Convert config.yaml"));
        assert!(toml.contains("[rule.align]"));
        assert!(toml.contains("fastq = \"data/{sample}.fastq\""));
        assert!(toml.contains("cpu = 8"));
        assert!(toml.contains("mem = \"16000M\""));
        assert!(toml.contains("conda = \"envs/alignment.yaml\""));
    }

    #[test]
    fn test_generate_config_values() {
        let ir = WorkflowIR {
            rules: vec![],
            config_file: None,
            includes: vec![],
            diagnostics: vec![],
            config_values: vec![
                ConfigEntryIR {
                    key: "samples".into(),
                    values: vec!["A".into(), "B".into(), "C".into()],
                },
                ConfigEntryIR {
                    key: "seed".into(),
                    values: vec!["42".into()],
                },
            ],
            escalations: vec![],
            global_container: None,
            global_report: None,
        };

        let toml = generate_oxymakefile(&ir);
        assert!(toml.contains("[config]"));
        assert!(toml.contains(r#"samples = ["A", "B", "C"]"#));
        assert!(toml.contains(r#"seed = "42""#));
    }

    #[test]
    fn test_generate_includes() {
        let ir = WorkflowIR {
            rules: vec![],
            config_file: None,
            includes: vec!["rules/align.smk".into(), "rules/qc.smk".into()],
            diagnostics: vec![],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        };

        let toml = generate_oxymakefile(&ir);
        assert!(toml.contains(r#""rules/align.toml""#));
        assert!(toml.contains(r#""rules/qc.toml""#));
    }

    #[test]
    fn test_generate_diagnostics() {
        let ir = WorkflowIR {
            rules: vec![],
            config_file: None,
            includes: vec![],
            diagnostics: vec![
                Diagnostic {
                    level: DiagLevel::Warning,
                    message: "test warning".into(),
                    line: Some(5),
                },
                Diagnostic {
                    level: DiagLevel::Error,
                    message: "test error".into(),
                    line: None,
                },
            ],
            config_values: vec![],
            escalations: vec![],
            global_container: None,
            global_report: None,
        };

        let toml = generate_oxymakefile(&ir);
        assert!(toml.contains("# WARNING (line 5): test warning"));
        assert!(toml.contains("# ERROR: test error"));
    }

    #[test]
    fn test_generate_run_block() {
        let mut rule = make_rule("analyze");
        rule.execution = ExecutionIR::Run("import json\nprint('hello')".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("lang = \"python\""));
        assert!(toml.contains("run = '''"));
        assert!(toml.contains("import json"));
    }

    #[test]
    fn test_generate_run_block_backslashes_survive_toml() {
        // Python code with escape sequences must round-trip through TOML
        // verbatim — a basic """ string would interpret `\n` at parse time.
        let mut rule = make_rule("analyze");
        rule.execution = ExecutionIR::Run(r#"print('\n'.join(['a', 'b']))"#.into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("run = '''"));
        assert!(toml.contains(r#"print('\n'.join(['a', 'b']))"#));
    }

    #[test]
    fn test_generate_run_block_with_triple_quotes_falls_back() {
        // Code containing ''' cannot live in a TOML literal string.
        let mut rule = make_rule("analyze");
        rule.execution = ExecutionIR::Run("x = '''doc'''\nprint(x)".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("run = \"\"\""));
        assert!(toml.contains("x = '''doc'''"));
    }

    #[test]
    fn test_generate_script() {
        let mut rule = make_rule("run_r");
        rule.execution = ExecutionIR::Script("scripts/analysis.R".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains(r#"script = "scripts/analysis.R""#));
    }

    #[test]
    fn test_generate_notebook() {
        let mut rule = make_rule("explore");
        rule.execution = ExecutionIR::Notebook("notebooks/explore.ipynb".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("# notebook translated as script"));
        assert!(toml.contains(r#"script = "notebooks/explore.ipynb""#));
    }

    #[test]
    fn test_generate_container() {
        let mut rule = make_rule("step");
        rule.environment = Some(EnvironmentIR::Container("docker://ubuntu:22.04".into()));
        rule.execution = ExecutionIR::Shell("echo".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains(r#"environment = { docker = "ubuntu:22.04" }"#));
    }

    #[test]
    fn test_generate_singularity() {
        let mut rule = make_rule("step");
        rule.environment = Some(EnvironmentIR::Singularity("image.sif".into()));
        rule.execution = ExecutionIR::Shell("echo".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains(r#"environment = { apptainer = "image.sif" }"#));
    }

    #[test]
    fn test_generate_wildcard_constraints() {
        let mut rule = make_rule("step");
        rule.wildcard_constraints = vec![("sample".into(), "[a-z]+".into())];
        rule.execution = ExecutionIR::Shell("echo".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("[rule.step.wildcard_constraints]"));
        assert!(toml.contains(r#"sample = "[a-z]+""#));
    }

    #[test]
    fn test_generate_expand_input() {
        let mut rule = make_rule("all");
        rule.inputs = vec![PortIR {
            name: None,
            pattern: "expand:results/{sample}.txt".into(),
            lifecycle: None,
        }];

        let toml = generate_rule(&rule);
        assert!(toml.contains(r#""results/{sample}.txt",  # TODO: configure expand variables"#));
    }

    #[test]
    fn test_generate_expand_product() {
        let mut rule = make_rule("all");
        rule.inputs = vec![PortIR {
            name: None,
            pattern: "results/{sample}.txt".into(),
            lifecycle: None,
        }];
        rule.expand = Some("product".into());

        let toml = generate_rule(&rule);
        assert!(
            toml.contains(r#"expand = "product""#),
            "Expected expand = \"product\" in:\n{}",
            toml
        );
    }

    #[test]
    fn test_generate_manual_input() {
        let mut rule = make_rule("all");
        rule.inputs = vec![PortIR {
            name: None,
            pattern: "# MANUAL: get_final_output()".into(),
            lifecycle: None,
        }];

        let toml = generate_rule(&rule);
        assert!(toml.contains("# MANUAL:  get_final_output()"));
    }

    #[test]
    fn test_generate_aggregation_rule() {
        let rule = make_rule("all");
        let toml = generate_rule(&rule);
        assert!(toml.contains("[rule.all]"));
        // No shell/run/script lines
        assert!(!toml.contains("shell"));
        assert!(!toml.contains("run"));
    }

    #[test]
    fn test_resource_translation() {
        assert_eq!(
            translate_resource("mem_mb", "16384"),
            ("mem".into(), "\"16G\"".into())
        );
        assert_eq!(
            translate_resource("mem_mb", "500"),
            ("mem".into(), "\"500M\"".into())
        );
        assert_eq!(
            translate_resource("mem_mb", "expr"),
            ("mem".into(), "\"exprM\"".into())
        );
        assert_eq!(
            translate_resource("disk_mb", "2048"),
            ("disk".into(), "\"2G\"".into())
        );
        assert_eq!(
            translate_resource("disk_mb", "500"),
            ("disk".into(), "\"500M\"".into())
        );
        assert_eq!(
            translate_resource("disk_mb", "expr"),
            ("disk".into(), "\"exprM\"".into())
        );
        assert_eq!(translate_resource("gpu", "2"), ("gpu".into(), "2".into()));
        assert_eq!(
            translate_resource("custom", "value,"),
            ("custom".into(), "\"value\"".into())
        );
    }

    #[test]
    fn test_escape_toml_string() {
        assert_eq!(escape_toml_string(r#"hello"world"#), r#"hello\"world"#);
        assert_eq!(escape_toml_string(r"path\to"), r"path\\to");
    }

    #[test]
    fn test_generate_multiline_shell() {
        let mut rule = make_rule("step");
        rule.execution = ExecutionIR::Shell("echo line1\necho line2".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("shell = \"\"\"\necho line1\necho line2\n\"\"\""));
    }

    #[test]
    fn test_generate_boolean_param() {
        let mut rule = make_rule("step");
        rule.params = vec![ParamIR {
            name: "flag".into(),
            value: "true".into(),
        }];
        rule.execution = ExecutionIR::Shell("echo".into());

        let toml = generate_rule(&rule);
        assert!(toml.contains("params = { flag = true }"));
    }
}
