//! Maps OxyMake's `MaterializePolicy` to Ray object store behavior.
//!
//! | MaterializePolicy | Ray Behavior                                             |
//! |-------------------|----------------------------------------------------------|
//! | `Always`          | Write to shared FS + put in object store                  |
//! | `Auto`            | Object store only (materialized if downstream needs file) |
//! | `Never`           | Object store only, evicted after consumers finish         |
//! | `Final`           | Object store → shared FS only for DAG leaves              |
//!
//! Object references are communicated between jobs via a JSON manifest file
//! written to the workspace directory. The scheduler reads this manifest
//! after job completion and passes object refs to downstream jobs via
//! environment variables.

use std::collections::HashMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use ox_core::model::MaterializePolicy;

/// Describes how a single output should be handled in the Ray object store.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjectStoreStrategy {
    /// Put the output data into the Ray object store via `ray.put()`.
    pub put_in_object_store: bool,
    /// Also write the output to the shared filesystem.
    pub write_to_shared_fs: bool,
    /// Whether the object store reference should be evicted after all
    /// consumers have retrieved it.
    pub evict_after_consumers: bool,
}

/// Map a `MaterializePolicy` to the corresponding Ray object store strategy.
pub fn strategy_for_policy(policy: MaterializePolicy, is_dag_leaf: bool) -> ObjectStoreStrategy {
    match policy {
        MaterializePolicy::Always => ObjectStoreStrategy {
            put_in_object_store: true,
            write_to_shared_fs: true,
            evict_after_consumers: false,
        },
        MaterializePolicy::Auto => ObjectStoreStrategy {
            put_in_object_store: true,
            write_to_shared_fs: false,
            evict_after_consumers: false,
        },
        MaterializePolicy::Never => ObjectStoreStrategy {
            put_in_object_store: true,
            write_to_shared_fs: false,
            evict_after_consumers: true,
        },
        MaterializePolicy::Final => ObjectStoreStrategy {
            put_in_object_store: true,
            write_to_shared_fs: is_dag_leaf,
            evict_after_consumers: false,
        },
    }
}

/// A reference to an object in the Ray object store, serialized as a hex string.
///
/// Object refs are opaque identifiers generated by `ray.put()` and consumed
/// by `ray.get()`. They are serialized to JSON for cross-job communication.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RayObjectRef {
    /// The hex-encoded object reference from `ray.put()`.
    pub object_ref_hex: String,
    /// Optional type hint for deserialization (e.g., "DataFrame", "ndarray").
    pub type_hint: Option<String>,
}

/// Manifest of object references produced by a job.
///
/// Written to `{workspace}/object_manifest.json` by the Python wrapper script.
/// The scheduler reads this after job completion to pass refs to downstream jobs.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ObjectManifest {
    /// Map from output name (or index string) to object reference.
    pub refs: HashMap<String, RayObjectRef>,
}

/// Well-known filename for the object manifest in the workspace directory.
pub const MANIFEST_FILENAME: &str = "object_manifest.json";

/// Read an object manifest from a workspace directory.
pub async fn read_manifest(workspace_dir: &Path) -> Result<ObjectManifest, std::io::Error> {
    let path = workspace_dir.join(MANIFEST_FILENAME);
    let contents = tokio::fs::read_to_string(&path).await?;
    serde_json::from_str(&contents).map_err(|e| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("failed to parse object manifest: {e}"),
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strategy_always() {
        let s = strategy_for_policy(MaterializePolicy::Always, false);
        assert!(s.put_in_object_store);
        assert!(s.write_to_shared_fs);
        assert!(!s.evict_after_consumers);
    }

    #[test]
    fn test_strategy_auto() {
        let s = strategy_for_policy(MaterializePolicy::Auto, false);
        assert!(s.put_in_object_store);
        assert!(!s.write_to_shared_fs);
        assert!(!s.evict_after_consumers);
    }

    #[test]
    fn test_strategy_never() {
        let s = strategy_for_policy(MaterializePolicy::Never, false);
        assert!(s.put_in_object_store);
        assert!(!s.write_to_shared_fs);
        assert!(s.evict_after_consumers);
    }

    #[test]
    fn test_strategy_final_non_leaf() {
        let s = strategy_for_policy(MaterializePolicy::Final, false);
        assert!(s.put_in_object_store);
        assert!(!s.write_to_shared_fs);
        assert!(!s.evict_after_consumers);
    }

    #[test]
    fn test_strategy_final_leaf() {
        let s = strategy_for_policy(MaterializePolicy::Final, true);
        assert!(s.put_in_object_store);
        assert!(s.write_to_shared_fs);
        assert!(!s.evict_after_consumers);
    }

    #[test]
    fn test_manifest_roundtrip() {
        let mut manifest = ObjectManifest::default();
        manifest.refs.insert(
            "output_0".into(),
            RayObjectRef {
                object_ref_hex: "abc123".into(),
                type_hint: Some("DataFrame".into()),
            },
        );

        let json = serde_json::to_string(&manifest).unwrap();
        let parsed: ObjectManifest = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.refs.len(), 1);
        assert_eq!(parsed.refs["output_0"].object_ref_hex, "abc123");
        assert_eq!(
            parsed.refs["output_0"].type_hint.as_deref(),
            Some("DataFrame")
        );
    }
}
